// <auto-generated />
using System;
using System.Collections.Generic;
using BellaHair.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BellaHair.Infrastructure.Migrations
{
    [DbContext(typeof(BellaHairContext))]
    [Migration("20251207210515_Setup")]
    partial class Setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BellaHair.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PaidDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TreatmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("_totalBase")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalBase");

                    b.Property<decimal?>("_totalWithDiscount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TotalWithDiscount");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.DiscountBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("BellaHair.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "BellaHair.Domain.Employees.Employee.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Floor")
                                .HasColumnType("int");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "BellaHair.Domain.Employees.Employee.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "BellaHair.Domain.Employees.Employee.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "BellaHair.Domain.Employees.Employee.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BellaHair.Domain.Invoices.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("InvoicePdf")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("BellaHair.Domain.PrivateCustomers.PrivateCustomer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("_birthdayDiscountUsedYears")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BirthdayDiscountUsedYears");

                    b.ComplexProperty<Dictionary<string, object>>("Address", "BellaHair.Domain.PrivateCustomers.PrivateCustomer.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("Floor")
                                .HasColumnType("int");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("StreetNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("ZipCode")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Email", "BellaHair.Domain.PrivateCustomers.PrivateCustomer.Email#Email", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Name", "BellaHair.Domain.PrivateCustomers.PrivateCustomer.Name#Name", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MiddleName")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("PhoneNumber", "BellaHair.Domain.PrivateCustomers.PrivateCustomer.PhoneNumber#PhoneNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("PrivateCustomers");
                });

            modelBuilder.Entity("BellaHair.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "BellaHair.Domain.Products.Product.Price#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BellaHair.Domain.Treatments.Treatment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty<Dictionary<string, object>>("DurationMinutes", "BellaHair.Domain.Treatments.Treatment.DurationMinutes#DurationMinutes", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Value")
                                .HasColumnType("int");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Price", "BellaHair.Domain.Treatments.Treatment.Price#Price", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Treatments");
                });

            modelBuilder.Entity("EmployeeTreatment", b =>
                {
                    b.Property<Guid>("EmployeesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TreatmentsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeesId", "TreatmentsId");

                    b.HasIndex("TreatmentsId");

                    b.ToTable("EmployeeTreatment");
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.BirthdayDiscount", b =>
                {
                    b.HasBaseType("BellaHair.Domain.Discounts.DiscountBase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("BirthdayDiscount");
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.CampaignDiscount", b =>
                {
                    b.HasBaseType("BellaHair.Domain.Discounts.DiscountBase");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("TreatmentIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CampaignDiscount");
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.LoyaltyDiscount", b =>
                {
                    b.HasBaseType("BellaHair.Domain.Discounts.DiscountBase");

                    b.Property<int>("MinimumVisits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("LoyaltyDiscount");
                });

            modelBuilder.Entity("BellaHair.Domain.Bookings.Booking", b =>
                {
                    b.HasOne("BellaHair.Domain.PrivateCustomers.PrivateCustomer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BellaHair.Domain.Employees.Employee", "Employee")
                        .WithMany("Bookings")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BellaHair.Domain.Treatments.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("BellaHair.Domain.Bookings.CustomerSnapshot", "CustomerSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("Birthday")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("BellaHair.Domain.Bookings.EmployeeSnapshot", "EmployeeSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("BellaHair.Domain.Bookings.ProductLine", "ProductLines", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("BookingId", "Id");

                            b1.HasIndex("ProductId");

                            b1.ToTable("ProductLine");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");

                            b1.HasOne("BellaHair.Domain.Products.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.OwnsOne("BellaHair.Domain.Bookings.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("ProductLineBookingId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("ProductLineId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("ProductLineBookingId", "ProductLineId");

                                    b2.ToTable("ProductLine");

                                    b2.WithOwner()
                                        .HasForeignKey("ProductLineBookingId", "ProductLineId");
                                });

                            b1.Navigation("Product");

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.OwnsMany("BellaHair.Domain.Bookings.ProductLineSnapshot", "ProductLineSnapshots", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("BookingId");

                            b1.ToTable("ProductLineSnapshot");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("BellaHair.Domain.Bookings.TreatmentSnapshot", "TreatmentSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DurationMinutes")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("TreatmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsOne("BellaHair.Domain.Discounts.BookingDiscount", "Discount", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<bool>("DiscountActive")
                                .HasColumnType("bit");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.HasKey("BookingId");

                            b1.ToTable("Bookings");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("Customer");

                    b.Navigation("CustomerSnapshot");

                    b.Navigation("Discount");

                    b.Navigation("Employee");

                    b.Navigation("EmployeeSnapshot");

                    b.Navigation("ProductLineSnapshots");

                    b.Navigation("ProductLines");

                    b.Navigation("Treatment");

                    b.Navigation("TreatmentSnapshot");
                });

            modelBuilder.Entity("BellaHair.Domain.Invoices.Invoice", b =>
                {
                    b.HasOne("BellaHair.Domain.Bookings.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("BellaHair.Domain.Invoices.Invoice", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("EmployeeTreatment", b =>
                {
                    b.HasOne("BellaHair.Domain.Employees.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BellaHair.Domain.Treatments.Treatment", null)
                        .WithMany()
                        .HasForeignKey("TreatmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.BirthdayDiscount", b =>
                {
                    b.OwnsOne("BellaHair.Domain.Discounts.DiscountPercent", "DiscountPercent", b1 =>
                        {
                            b1.Property<Guid>("BirthdayDiscountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("BirthdayDiscountId");

                            b1.ToTable("BirthdayDiscount");

                            b1.WithOwner()
                                .HasForeignKey("BirthdayDiscountId");
                        });

                    b.Navigation("DiscountPercent")
                        .IsRequired();
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.CampaignDiscount", b =>
                {
                    b.OwnsOne("BellaHair.Domain.Discounts.DiscountPercent", "DiscountPercent", b1 =>
                        {
                            b1.Property<Guid>("CampaignDiscountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("CampaignDiscountId");

                            b1.ToTable("CampaignDiscount");

                            b1.WithOwner()
                                .HasForeignKey("CampaignDiscountId");
                        });

                    b.Navigation("DiscountPercent")
                        .IsRequired();
                });

            modelBuilder.Entity("BellaHair.Domain.Discounts.LoyaltyDiscount", b =>
                {
                    b.OwnsOne("BellaHair.Domain.Discounts.DiscountPercent", "ProductDiscountPercent", b1 =>
                        {
                            b1.Property<Guid>("LoyaltyDiscountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("LoyaltyDiscountId");

                            b1.ToTable("LoyaltyDiscount");

                            b1.WithOwner()
                                .HasForeignKey("LoyaltyDiscountId");
                        });

                    b.OwnsOne("BellaHair.Domain.Discounts.DiscountPercent", "TreatmentDiscountPercent", b1 =>
                        {
                            b1.Property<Guid>("LoyaltyDiscountId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,2)");

                            b1.HasKey("LoyaltyDiscountId");

                            b1.ToTable("LoyaltyDiscount");

                            b1.WithOwner()
                                .HasForeignKey("LoyaltyDiscountId");
                        });

                    b.Navigation("ProductDiscountPercent");

                    b.Navigation("TreatmentDiscountPercent")
                        .IsRequired();
                });

            modelBuilder.Entity("BellaHair.Domain.Bookings.Booking", b =>
                {
                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("BellaHair.Domain.Employees.Employee", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BellaHair.Domain.PrivateCustomers.PrivateCustomer", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
